name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - name: Set environment variables
      run: |
        touch .env
        echo "PROD_SECRET=${{ secrets.PROD_SECRET }}" > .env

    - name: Build the application
      run: npm run build

    - name: Install PM2
      run: npm install -g pm2

    - name: Start application with PM2
      run: pm2 restart dist/index.js --interpreter node
